Repository GDSC-DGU/2025-APAC-SolutionChallenge-Circulo, pull requests merged in 2025-05, with the labels that each got.

#23 [setting/#2] design system 추가
  client/app/src/main/java/com/example/circuler/presentation/dummy/ReqresRoute.kt
  client/app/src/main/java/com/example/circuler/ui/theme/Color.kt
  client/app/src/main/java/com/example/circuler/ui/theme/Theme.kt
  client/app/src/main/java/com/example/circuler/ui/theme/Type.kt
Labels: ⚙ Setting

#25 [setting/#7] 서버 세팅
  server/.gitattributes
  server/.gitignore
  server/build.gradle
  server/gradle/wrapper/gradle-wrapper.jar
  server/gradle/wrapper/gradle-wrapper.properties
  server/gradlew
  server/gradlew.bat
  server/settings.gradle
  server/src/main/java/circulo/server/ServerApplication.java
  server/src/main/java/circulo/server/domain/delivery/entity/Delivery.java
  server/src/main/java/circulo/server/domain/delivery/entity/enums/DeliveryStatus.java
  server/src/main/java/circulo/server/domain/packageSubmission/entity/PackageSubmission.java
  server/src/main/java/circulo/server/domain/packageSubmission/entity/enums/DeliveryMethod.java
  server/src/main/java/circulo/server/domain/packagingRequest/entity/PackagingRequest.java
  server/src/main/java/circulo/server/domain/packagingRequest/entity/enums/PackagingRequestStatus.java
  server/src/main/java/circulo/server/domain/packagingRequest/entity/enums/PackagingType.java
  server/src/main/java/circulo/server/domain/user/entity/User.java
  server/src/main/java/circulo/server/global/common/domain/BaseEntity.java
  server/src/test/java/circulo/server/ServerApplicationTests.java
Labels: ⚙ Setting

#26 [refactor/#15] Entity 수정
  README.md
  server/src/main/java/circulo/server/domain/delivery/entity/Delivery.java
  server/src/main/java/circulo/server/domain/packageSubmission/entity/PackageSubmission.java
Labels: 🔨 Refactor

#27 [setting/#17] Swagger 세팅
  server/build.gradle
  server/src/main/java/circulo/server/global/common/config/SwaggerConfig.java
Labels: ⚙ Setting

#29 [setting/#14] navigation 세팅
  client/app/src/main/java/com/example/circuler/presentation/core/util/ConvertDpToFloat.kt
  client/app/src/main/java/com/example/circuler/presentation/navigator/MainActivity.kt
  client/app/src/main/java/com/example/circuler/presentation/navigator/MainNavigator.kt
  client/app/src/main/java/com/example/circuler/presentation/navigator/MainScreen.kt
  client/app/src/main/java/com/example/circuler/presentation/navigator/component/CirculoNavHost.kt
  client/app/src/main/java/com/example/circuler/presentation/navigator/component/MainBottomBar.kt
  client/app/src/main/java/com/example/circuler/presentation/navigator/route/Route.kt
  client/app/src/main/java/com/example/circuler/presentation/type/MainTabType.kt
  client/app/src/main/java/com/example/circuler/presentation/ui/history/HistoryRoute.kt
  client/app/src/main/java/com/example/circuler/presentation/ui/history/HistorySideEffect.kt
  client/app/src/main/java/com/example/circuler/presentation/ui/history/HistoryState.kt
  client/app/src/main/java/com/example/circuler/presentation/ui/history/HistoryViewModel.kt
  client/app/src/main/java/com/example/circuler/presentation/ui/history/navigation/HistoryNavigation.kt
  client/app/src/main/java/com/example/circuler/presentation/ui/home/HomeRoute.kt
  client/app/src/main/java/com/example/circuler/presentation/ui/home/HomeSideEffect.kt
  client/app/src/main/java/com/example/circuler/presentation/ui/home/HomeState.kt
  client/app/src/main/java/com/example/circuler/presentation/ui/home/HomeViewModel.kt
  client/app/src/main/java/com/example/circuler/presentation/ui/home/navigation/HomeNavigation.kt
  client/app/src/main/res/values/strings.xml
Labels: ⚙ Setting

#31 [feature/#12] Spring Security 기반 구글 소셜 로그인 구현
  server/.gitignore
  server/build.gradle
  server/src/main/java/circulo/server/ServerApplication.java
  server/src/main/java/circulo/server/domain/auth/controller/AuthController.java
  server/src/main/java/circulo/server/domain/auth/converter/AuthConverter.java
  server/src/main/java/circulo/server/domain/user/entity/User.java
  server/src/main/java/circulo/server/domain/user/repository/UserRepository.java
  server/src/main/java/circulo/server/global/apiPayload/ApiResponse.java
  server/src/main/java/circulo/server/global/apiPayload/code/BaseCode.java
  server/src/main/java/circulo/server/global/apiPayload/code/BaseErrorCode.java
  server/src/main/java/circulo/server/global/apiPayload/code/ErrorReasonDTO.java
  server/src/main/java/circulo/server/global/apiPayload/code/ReasonDTO.java
  server/src/main/java/circulo/server/global/apiPayload/code/exception/GeneralException.java
  server/src/main/java/circulo/server/global/apiPayload/code/exception/custom/AuthException.java
  server/src/main/java/circulo/server/global/apiPayload/code/exception/custom/BadRequestException.java
  server/src/main/java/circulo/server/global/apiPayload/code/exception/custom/TokenException.java
  server/src/main/java/circulo/server/global/apiPayload/code/status/ErrorStatus.java
  server/src/main/java/circulo/server/global/apiPayload/code/status/SuccessStatus.java
  server/src/main/java/circulo/server/global/config/SwaggerConfig.java
  server/src/main/java/circulo/server/global/redis/RedisConfig.java
  server/src/main/java/circulo/server/global/security/SecurityConfig.java
  server/src/main/java/circulo/server/global/security/jwt/JwtTokenFilter.java
  server/src/main/java/circulo/server/global/security/jwt/JwtTokenProvider.java
  server/src/main/java/circulo/server/global/security/jwt/TokenInfo.java
  server/src/main/java/circulo/server/global/security/oauth/CustomOAuth2User.java
  server/src/main/java/circulo/server/global/security/oauth/CustomOauth2UserService.java
  server/src/main/java/circulo/server/global/security/oauth/OAuth2SuccessHandler.java
  server/src/main/java/circulo/server/global/security/oauth/OAuth2UserInfo.java
Labels: :sparkles: Feature

#32 [feature/#30] home UI 구현
  client/app/src/main/java/com/example/circuler/presentation/core/component/CirculoTopBar.kt
  client/app/src/main/java/com/example/circuler/presentation/navigator/MainNavigator.kt
  client/app/src/main/java/com/example/circuler/presentation/navigator/component/CirculoNavHost.kt
  client/app/src/main/java/com/example/circuler/presentation/type/HomeNavigateButtonType.kt
  client/app/src/main/java/com/example/circuler/presentation/ui/add/AddPackagingRoute.kt
  client/app/src/main/java/com/example/circuler/presentation/ui/add/AddPackagingSideEffect.kt
  client/app/src/main/java/com/example/circuler/presentation/ui/add/AddPackagingState.kt
  client/app/src/main/java/com/example/circuler/presentation/ui/add/AddPackagingViewModel.kt
  client/app/src/main/java/com/example/circuler/presentation/ui/add/navigation/AddPackagingNavigation.kt
  client/app/src/main/java/com/example/circuler/presentation/ui/delivery/DeliveryRoute.kt
  client/app/src/main/java/com/example/circuler/presentation/ui/delivery/DeliverySideEffect.kt
  client/app/src/main/java/com/example/circuler/presentation/ui/delivery/DeliveryState.kt
  client/app/src/main/java/com/example/circuler/presentation/ui/delivery/DeliveryViewModel.kt
  client/app/src/main/java/com/example/circuler/presentation/ui/delivery/navigation/DeliveryNavigation.kt
  client/app/src/main/java/com/example/circuler/presentation/ui/home/HomeRoute.kt
  client/app/src/main/java/com/example/circuler/presentation/ui/home/HomeSideEffect.kt
  client/app/src/main/java/com/example/circuler/presentation/ui/home/HomeViewModel.kt
  client/app/src/main/java/com/example/circuler/presentation/ui/home/component/HomeMainButton.kt
  client/app/src/main/java/com/example/circuler/presentation/ui/home/component/HomeNavigateButton.kt
  client/app/src/main/java/com/example/circuler/presentation/ui/home/navigation/HomeNavigation.kt
  client/app/src/main/java/com/example/circuler/presentation/ui/request/RequestRoute.kt
  client/app/src/main/java/com/example/circuler/presentation/ui/request/RequestSideEffect.kt
  client/app/src/main/java/com/example/circuler/presentation/ui/request/RequestState.kt
  client/app/src/main/java/com/example/circuler/presentation/ui/request/RequestViewModel.kt
  client/app/src/main/java/com/example/circuler/presentation/ui/request/navigation/RequestNavigation.kt
  client/app/src/main/res/drawable/ic_add_circle.xml
  client/app/src/main/res/drawable/ic_arrow_left.xml
  client/app/src/main/res/drawable/ic_box.xml
  client/app/src/main/res/drawable/ic_point.xml
  client/app/src/main/res/drawable/ic_request.xml
  client/app/src/main/res/drawable/img_add_packaging.png
  client/app/src/main/res/drawable/img_circulo_logo_small.png
  client/app/src/main/res/values/strings.xml
Labels: :sparkles: Feature

#35 [refactor/#34] Auth Resolver 및 status 값 수정
  server/src/main/java/circulo/server/domain/packagingRequest/entity/enums/PackagingRequestStatus.java
  server/src/main/java/circulo/server/global/apiPayload/code/status/ErrorStatus.java
  server/src/main/java/circulo/server/global/handler/annotation/Auth.java
  server/src/main/java/circulo/server/global/handler/resolver/AuthResolver.java
Labels: 🔨 Refactor, :sparkles: Feature

#36 [refactor/#34] @Auth 어노테이션 활성화
  server/src/main/java/circulo/server/global/config/WebConfig.java
  server/src/main/java/circulo/server/global/security/jwt/JwtTokenProvider.java
Labels: 🔨 Refactor

#45 [feature/#28] 소상공인 본인이 올린 포장재 요청글 리스트 조회 기능 구현
  server/src/main/java/circulo/server/domain/packagingRequest/controller/PackagingRequestController.java
  server/src/main/java/circulo/server/domain/packagingRequest/converter/PackagingRequestConverter.java
  server/src/main/java/circulo/server/domain/packagingRequest/dto/response/PackagingRequestResponse.java
  server/src/main/java/circulo/server/domain/packagingRequest/repository/PackagingRequestRepository.java
  server/src/main/java/circulo/server/domain/packagingRequest/service/PackagingRequestQueryService.java
  server/src/main/java/circulo/server/domain/packagingRequest/service/PackagingRequestQueryServiceImpl.java
Labels: :sparkles: Feature

#46 [feature/#41] 포장재 전달 신청 관련 API 구현
  server/src/main/java/circulo/server/domain/packageSubmission/controller/PackageSubmissionController.java
  server/src/main/java/circulo/server/domain/packageSubmission/converter/PackageSubmissionConverter.java
  server/src/main/java/circulo/server/domain/packageSubmission/dto/request/PackageSubmissionRequest.java
  server/src/main/java/circulo/server/domain/packageSubmission/dto/response/PackageSubmissionResponse.java
  server/src/main/java/circulo/server/domain/packageSubmission/entity/PackageSubmission.java
  server/src/main/java/circulo/server/domain/packageSubmission/entity/enums/PackageSubmissionStatus.java
  server/src/main/java/circulo/server/domain/packageSubmission/repository/PackageSubmissionRepository.java
  server/src/main/java/circulo/server/domain/packageSubmission/service/PackageSubmissionCommandService.java
  server/src/main/java/circulo/server/domain/packageSubmission/service/PackageSubmissionCommandServiceImpl.java
  server/src/main/java/circulo/server/domain/packageSubmission/service/PackageSubmissionQueryService.java
  server/src/main/java/circulo/server/domain/packageSubmission/service/PackageSubmissionQueryServiceImpl.java
  server/src/main/java/circulo/server/domain/packagingRequest/controller/PackagingRequestController.java
  server/src/main/java/circulo/server/domain/packagingRequest/converter/PackagingRequestConverter.java
  server/src/main/java/circulo/server/domain/packagingRequest/dto/response/PackagingRequestResponse.java
  server/src/main/java/circulo/server/domain/packagingRequest/entity/PackagingRequest.java
  server/src/main/java/circulo/server/domain/packagingRequest/entity/enums/PackagingRequestStatus.java
  server/src/main/java/circulo/server/domain/packagingRequest/service/PackagingRequestCommandService.java
  server/src/main/java/circulo/server/domain/packagingRequest/service/PackagingRequestCommandServiceImpl.java
  server/src/main/java/circulo/server/domain/packagingRequest/service/PackagingRequestQueryService.java
  server/src/main/java/circulo/server/domain/packagingRequest/service/PackagingRequestQueryServiceImpl.java
  server/src/main/java/circulo/server/global/apiPayload/ApiResponse.java
  server/src/main/java/circulo/server/global/apiPayload/code/exception/custom/PackageSubmissionException.java
  server/src/main/java/circulo/server/global/apiPayload/code/status/ErrorStatus.java
  server/src/main/java/circulo/server/global/security/CustomAuthenticationEntryPoint.java
  server/src/main/java/circulo/server/global/security/SecurityConfig.java
Labels: :sparkles: Feature

#50 [feature/#44] 배달 매칭 관련 API 구현
  server/src/main/java/circulo/server/domain/delivery/controller/DeliveryController.java
  server/src/main/java/circulo/server/domain/delivery/converter/DeliveryConverter.java
  server/src/main/java/circulo/server/domain/delivery/dto/response/DeliveryResponse.java
  server/src/main/java/circulo/server/domain/delivery/entity/Delivery.java
  server/src/main/java/circulo/server/domain/delivery/repository/DeliveryRepository.java
  server/src/main/java/circulo/server/domain/delivery/service/DeliveryCommandService.java
  server/src/main/java/circulo/server/domain/delivery/service/DeliveryCommandServiceImpl.java
  server/src/main/java/circulo/server/domain/delivery/service/DeliveryQueryService.java
  server/src/main/java/circulo/server/domain/delivery/service/DeliveryQueryServiceImpl.java
  server/src/main/java/circulo/server/global/apiPayload/code/exception/custom/DeliveryException.java
  server/src/main/java/circulo/server/global/apiPayload/code/status/ErrorStatus.java
Labels: :sparkles: Feature

#51 [feature/#43] 배달 완료 처리 구현
  server/src/main/java/circulo/server/domain/delivery/entity/Delivery.java
  server/src/main/java/circulo/server/domain/delivery/repository/DeliveryRepository.java
  server/src/main/java/circulo/server/domain/packageSubmission/controller/PackageSubmissionController.java
  server/src/main/java/circulo/server/domain/packageSubmission/service/PackageSubmissionCommandService.java
  server/src/main/java/circulo/server/domain/packageSubmission/service/PackageSubmissionCommandServiceImpl.java
Labels: :sparkles: Feature

#59 [feature/#48] google login 연결
  client/app/build.gradle.kts
  client/app/src/main/java/com/example/circuler/data/datalocal/datasource/TokenDataSource.kt
  client/app/src/main/java/com/example/circuler/data/datalocal/datasourceimpl/TokenDataSourceImpl.kt
  client/app/src/main/java/com/example/circuler/data/datasource/GoogleDataSource.kt
  client/app/src/main/java/com/example/circuler/data/datasource/RequestDataSource.kt
  client/app/src/main/java/com/example/circuler/data/datasource/UserDataSource.kt
  client/app/src/main/java/com/example/circuler/data/di/DataSourceModule.kt
  client/app/src/main/java/com/example/circuler/data/di/RepositoryModule.kt
  client/app/src/main/java/com/example/circuler/data/di/ServiceModule.kt
  client/app/src/main/java/com/example/circuler/data/di/SharedPreferencesModule.kt
  client/app/src/main/java/com/example/circuler/data/dto/request/RequestPackageDto.kt
  client/app/src/main/java/com/example/circuler/data/dto/response/BaseResponse.kt
  client/app/src/main/java/com/example/circuler/data/dto/response/ResponseListDataDto.kt
  client/app/src/main/java/com/example/circuler/data/dto/response/ResponseLoginDto.kt
  client/app/src/main/java/com/example/circuler/data/dto/response/ResponsePackagingListDto.kt
  client/app/src/main/java/com/example/circuler/data/dto/response/ResponseRequestPackageDto.kt
  client/app/src/main/java/com/example/circuler/data/repositoryimpl/RequestRepositoryImpl.kt
  client/app/src/main/java/com/example/circuler/data/repositoryimpl/TokenRepositoryImpl.kt
  client/app/src/main/java/com/example/circuler/data/repositoryimpl/UserRepositoryImpl.kt
  client/app/src/main/java/com/example/circuler/data/service/RequestService.kt
  client/app/src/main/java/com/example/circuler/data/service/UserService.kt
  client/app/src/main/java/com/example/circuler/domain/entity/AddPackagingEntity.kt
  client/app/src/main/java/com/example/circuler/domain/entity/TokenEntity.kt
  client/app/src/main/java/com/example/circuler/domain/repository/RequestRepository.kt
  client/app/src/main/java/com/example/circuler/domain/repository/TokenRepository.kt
  client/app/src/main/java/com/example/circuler/domain/repository/UserRepository.kt
  client/app/src/main/java/com/example/circuler/presentation/ui/add/AddPackagingRoute.kt
  client/app/src/main/java/com/example/circuler/presentation/ui/add/AddPackagingState.kt
  client/app/src/main/java/com/example/circuler/presentation/ui/add/AddPackagingViewModel.kt
  client/app/src/main/java/com/example/circuler/presentation/ui/login/LoginRoute.kt
  client/app/src/main/java/com/example/circuler/presentation/ui/login/LoginSideEffect.kt
  client/app/src/main/java/com/example/circuler/presentation/ui/login/LoginViewModel.kt
  client/gradle/libs.versions.toml
Labels: :sparkles: Feature

#58 [refactor/#57] 구글 소셜 로그인 오류 관련 수정
  server/src/main/java/circulo/server/global/security/SecurityConfig.java
  server/src/main/java/circulo/server/global/security/jwt/JwtTokenProvider.java
  server/src/main/java/circulo/server/global/security/oauth/CustomOauth2UserService.java
  server/src/main/java/circulo/server/global/security/oauth/OAuth2SuccessHandler.java
Labels: 🔨 Refactor

#56 [deploy/#55] 서버 CI/CD 구축
  .github/workflows/circuler_server_cd.yml
  .github/workflows/circuler_server_ci.yml
  server/.gitignore
  server/Dockerfile
  server/docker-compose.yml
  server/src/main/resources/application.yml
Labels: :rocket: Deploy

#63 [feature/#62] change Circulo app icon
  client/app/src/main/res/drawable/ic_launcher_background.xml
  client/app/src/main/res/drawable/ic_launcher_foreground.xml
  client/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  client/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  client/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  client/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  client/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  client/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  client/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  client/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  client/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  client/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  client/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  client/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  client/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  client/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  client/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  client/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  client/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
Labels: :sparkles: Feature

#67 [chore/#66] change Circulo app icon
  client/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  client/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  client/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  client/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  client/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  client/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  client/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  client/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  client/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  client/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  client/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  client/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  client/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  client/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  client/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
Labels: 🛠️ Chore

#65 [feature/#64] 포장재 사진 등록 API 구현
  .github/workflows/circuler_server_ci.yml
  server/src/main/java/circulo/server/domain/packageSubmission/controller/PackageSubmissionController.java
  server/src/main/java/circulo/server/domain/packageSubmission/converter/PackageSubmissionConverter.java
  server/src/main/java/circulo/server/domain/packageSubmission/dto/response/PackageSubmissionResponse.java
  server/src/main/java/circulo/server/domain/packageSubmission/entity/PackageSubmission.java
  server/src/main/java/circulo/server/domain/packageSubmission/service/PackageSubmissionCommandService.java
  server/src/main/java/circulo/server/domain/packageSubmission/service/PackageSubmissionCommandServiceImpl.java
  server/src/main/java/circulo/server/domain/packageSubmission/service/VertexAIService.java
  server/src/main/java/circulo/server/global/apiPayload/code/status/ErrorStatus.java
  server/src/main/resources/application.yml
Labels: :sparkles: Feature

#70 [refactor/#64] docker-compose.yml 수정
  server/docker-compose.yml
Labels: 🔨 Refactor

#72 [refactor/#64] 로그 확인할 수 있도록 수정
  server/src/main/java/circulo/server/domain/packageSubmission/service/VertexAIService.java
Labels: 🔨 Refactor

#77 [refactor/#74] Delivery 객체 생성하도록 수정
  server/src/main/java/circulo/server/domain/packageSubmission/service/PackageSubmissionCommandServiceImpl.java
Labels: 🔨 Refactor

#75 [feature/#68] upload image
  client/app/build.gradle.kts
  client/app/src/main/AndroidManifest.xml
  client/app/src/main/java/com/example/circuler/data/datasource/SubmissionDataSource.kt
  client/app/src/main/java/com/example/circuler/data/dto/response/ResponsePackageImageDto.kt
  client/app/src/main/java/com/example/circuler/data/repositoryimpl/SubmissionRepositoryImpl.kt
  client/app/src/main/java/com/example/circuler/data/service/RequestService.kt
  client/app/src/main/java/com/example/circuler/data/service/SubmissionService.kt
  client/app/src/main/java/com/example/circuler/domain/entity/PackageImageEntity.kt
  client/app/src/main/java/com/example/circuler/domain/repository/SubmissionRepository.kt
  client/app/src/main/java/com/example/circuler/presentation/core/network/ContentUriRequestBody.kt
  client/app/src/main/java/com/example/circuler/presentation/core/util/UiState.kt
  client/app/src/main/java/com/example/circuler/presentation/ui/upload/UploadPackagingRoute.kt
  client/app/src/main/java/com/example/circuler/presentation/ui/upload/UploadPackagingState.kt
  client/app/src/main/java/com/example/circuler/presentation/ui/upload/UploadPackagingViewModel.kt
  client/app/src/main/java/com/example/circuler/presentation/ui/upload/camerax/CameraX.kt
  client/app/src/main/java/com/example/circuler/presentation/ui/upload/camerax/CameraXFactory.kt
  client/app/src/main/java/com/example/circuler/presentation/ui/upload/camerax/CameraXImpl.kt
  client/app/src/main/res/xml/file_paths.xml
  client/gradle/libs.versions.toml
Labels: :sparkles: Feature

#78 [fix/#76] qa
  client/app/src/main/java/com/example/circuler/data/datasource/RequestDataSource.kt
  client/app/src/main/java/com/example/circuler/data/repositoryimpl/RequestRepositoryImpl.kt
  client/app/src/main/java/com/example/circuler/data/service/RequestService.kt
  client/app/src/main/java/com/example/circuler/presentation/core/component/CirculoChip.kt
  client/app/src/main/java/com/example/circuler/presentation/core/component/CirculoListCard.kt
  client/app/src/main/java/com/example/circuler/presentation/type/StatusType.kt
  client/app/src/main/java/com/example/circuler/presentation/ui/confirm/component/CirculoTextGroup.kt
  client/app/src/main/java/com/example/circuler/presentation/ui/delivery/DeliveryRoute.kt
  client/app/src/main/java/com/example/circuler/presentation/ui/home/component/HomeNavigateButton.kt
  client/app/src/main/java/com/example/circuler/presentation/ui/map/MapRoute.kt
  client/app/src/main/java/com/example/circuler/presentation/ui/request/component/RequestSortButton.kt
Labels: :bug: BugFix, 🛠️ Chore, 🔨 Refactor
